spring:
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
  jpa:
    database: POSTGRESQL
    properties:
      hibernate:
        show_sql: true
  datasource:
    url: jdbc:postgresql://localhost:5433/rcdb
    username: postgres
    password: root
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres